<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e5c471d0-3ecc-4ea9-ab31-d5e9f0fa03aa</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
		<PackageReference Include="CloudinaryDotNet" Version="1.29.2" />
		<PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
		<PackageReference Include="GoogleAuthenticator" Version="3.2.0" />
		<PackageReference Include="MailKit" Version="4.17.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.OData" Version="9.5.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
		<PackageReference Include="payOS" Version="2.1.0" />
		<PackageReference Include="StackExchange.Redis" Version="3.0.25" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	</ItemGroup>

<!-- loai bo project tests khoi viec compile khi project build -->
  <ItemGroup>
    <Compile Remove="MenuGoTest.UnitTests\**" />
    <Content Remove="MenuGoTest.UnitTests\**" />
    <EmbeddedResource Remove="MenuGoTest.UnitTests\**" />
    <None Remove="MenuGoTest.UnitTests\**" />
  </ItemGroup>

</Project>
