using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MenuGoBE.Migrations
{
    /// <inheritdoc />
    public partial class RecreateDocumentCoreTablesClean : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. Drop existing tables if present
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"InventoryLedgers\" CASCADE;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"DocumentDetails\" CASCADE;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"Documents\" CASCADE;");

            // 2. Recreate Documents table
            migrationBuilder.Sql(@"
                CREATE TABLE public.""Documents"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""BranchId"" bigint NOT NULL,
                    ""ToBranchId"" bigint NULL,
                    ""PartnerId"" bigint NULL,
                    ""ParentDocumentId"" bigint NULL,
                    ""PostingSequence"" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""OrderDate"" timestamp with time zone NOT NULL,
                    ""Code"" character varying(100) NOT NULL,
                    ""Type"" text NOT NULL,
                    ""Status"" text NOT NULL,
                    ""TransferStatus"" text NOT NULL,
                    ""SnapshotBranchName"" character varying(255) NOT NULL DEFAULT '',
                    ""SnapshotToBranchName"" character varying(255) NULL,
                    ""SnapshotPartnerName"" character varying(255) NULL,
                    ""CreatedBy"" bigint NULL,
                    ""SnapshotCreatedByName"" character varying(255) NULL,
                    ""SnapshotCreatedByUsername"" character varying(100) NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ""PostedBy"" bigint NULL,
                    ""SnapshotPostedByName"" character varying(255) NULL,
                    ""SnapshotPostedByUsername"" character varying(100) NULL,
                    ""PostedAt"" timestamp with time zone NULL,
                    ""IsDeleted"" boolean NOT NULL DEFAULT false,
                    ""DeletedBy"" bigint NULL,
                    ""SnapshotDeletedByName"" character varying(255) NULL,
                    ""DeletedAt"" timestamp with time zone NULL,
                    ""TotalAmount"" numeric(108, 12) NOT NULL DEFAULT 0,
                    ""AmountDue"" numeric(108, 12) NULL,
                    ""AmountPaid"" numeric(108, 12) NOT NULL DEFAULT 0,
                    ""Note"" text NULL,
                    ""DeleteNote"" text NULL,
                    CONSTRAINT ""PK_Documents"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Documents_Branches_BranchId"" FOREIGN KEY (""BranchId"") REFERENCES ""Branches"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_Documents_Branches_ToBranchId"" FOREIGN KEY (""ToBranchId"") REFERENCES ""Branches"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_Documents_Partners_PartnerId"" FOREIGN KEY (""PartnerId"") REFERENCES ""Partners"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_Documents_Documents_ParentDocumentId"" FOREIGN KEY (""ParentDocumentId"") REFERENCES ""Documents"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_Documents_Accounts_CreatedBy"" FOREIGN KEY (""CreatedBy"") REFERENCES ""Accounts"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_Documents_Accounts_PostedBy"" FOREIGN KEY (""PostedBy"") REFERENCES ""Accounts"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_Documents_Accounts_DeletedBy"" FOREIGN KEY (""DeletedBy"") REFERENCES ""Accounts"" (""Id"") ON DELETE RESTRICT
                );
            ");

            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Documents_Code"" ON public.""Documents"" (""Code"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Documents_BranchId"" ON public.""Documents"" (""BranchId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Documents_ToBranchId"" ON public.""Documents"" (""ToBranchId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Documents_PartnerId"" ON public.""Documents"" (""PartnerId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Documents_ParentDocumentId"" ON public.""Documents"" (""ParentDocumentId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Documents_CreatedBy"" ON public.""Documents"" (""CreatedBy"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Documents_PostedBy"" ON public.""Documents"" (""PostedBy"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Documents_DeletedBy"" ON public.""Documents"" (""DeletedBy"");");

            // 3. Recreate DocumentDetails table
            migrationBuilder.Sql(@"
                CREATE TABLE public.""DocumentDetails"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""DocumentId"" bigint NOT NULL,
                    ""BInventoryId"" bigint NOT NULL,
                    ""FatherId"" bigint NULL,
                    ""UnitConversionId"" bigint NULL,
                    ""SnapshotProductName"" character varying(255) NOT NULL DEFAULT '',
                    ""SnapshotProductCode"" character varying(100) NOT NULL DEFAULT '',
                    ""SnapshotUnitName"" character varying(100) NOT NULL DEFAULT '',
                    ""SnapshotBaseUnitName"" character varying(100) NOT NULL DEFAULT '',
                    ""ConversionRate"" numeric(18, 6) NOT NULL DEFAULT 1,
                    ""Quantity"" numeric(51, 3) NOT NULL DEFAULT 0,
                    ""BaseQuantity"" numeric(51, 3) NOT NULL DEFAULT 0,
                    ""UnitPrice"" numeric(108, 12) NOT NULL DEFAULT 0,
                    ""SnapshotAvgCost"" numeric(108, 12) NOT NULL DEFAULT 0,
                    ""SystemQuantity"" numeric(51, 3) NULL,
                    ""ActualQuantity"" numeric(51, 3) NULL,
                    ""AdjustedCostDelta"" numeric(108, 12) NULL,
                    ""NewAvgCost"" numeric(108, 12) NULL,
                    ""IsDeleted"" boolean NOT NULL DEFAULT false,
                    ""Note"" text NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ""PK_DocumentDetails"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_DocumentDetails_Documents_DocumentId"" FOREIGN KEY (""DocumentId"") REFERENCES ""Documents"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_DocumentDetails_BInventories_BInventoryId"" FOREIGN KEY (""BInventoryId"") REFERENCES ""BInventories"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_DocumentDetails_DocumentDetails_FatherId"" FOREIGN KEY (""FatherId"") REFERENCES ""DocumentDetails"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_DocumentDetails_UnitConversions_UnitConversionId"" FOREIGN KEY (""UnitConversionId"") REFERENCES ""UnitConversions"" (""Id"") ON DELETE RESTRICT
                );
            ");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DocumentDetails_DocumentId"" ON public.""DocumentDetails"" (""DocumentId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DocumentDetails_BInventoryId"" ON public.""DocumentDetails"" (""BInventoryId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DocumentDetails_FatherId"" ON public.""DocumentDetails"" (""FatherId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DocumentDetails_UnitConversionId"" ON public.""DocumentDetails"" (""UnitConversionId"");");

            // 4. Recreate InventoryLedgers table (No relationship/FK to DocumentDetails)
            migrationBuilder.Sql(@"
                CREATE TABLE public.""InventoryLedgers"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""BInventoryId"" bigint NOT NULL,
                    ""DocumentId"" bigint NULL,
                    ""PostingSequence"" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""PostedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ""DocumentType"" text NOT NULL,
                    ""PostedBy"" bigint NOT NULL DEFAULT 0,
                    ""SnapshotPostedByName"" character varying(255) NOT NULL DEFAULT '',
                    ""SnapshotBranchName"" character varying(255) NOT NULL DEFAULT '',
                    ""SnapshotProductName"" character varying(255) NOT NULL DEFAULT '',
                    ""SnapshotUnitName"" character varying(100) NOT NULL DEFAULT '',
                    ""QuantityDelta"" numeric(51, 3) NOT NULL DEFAULT 0,
                    ""InventoryValueDelta"" numeric(108, 12) NOT NULL DEFAULT 0,
                    ""RunningQuantity"" numeric(51, 3) NOT NULL DEFAULT 0,
                    ""RunningInventoryValue"" numeric(108, 12) NOT NULL DEFAULT 0,
                    ""RunningAverageCost"" numeric(108, 12) NOT NULL DEFAULT 0,
                    ""UnitCost"" numeric(108, 12) NOT NULL DEFAULT 0,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ""PK_InventoryLedgers"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_InventoryLedgers_BInventories_BInventoryId"" FOREIGN KEY (""BInventoryId"") REFERENCES ""BInventories"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_InventoryLedgers_Documents_DocumentId"" FOREIGN KEY (""DocumentId"") REFERENCES ""Documents"" (""Id"") ON DELETE RESTRICT
                );
            ");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_InventoryLedgers_BInventoryId"" ON public.""InventoryLedgers"" (""BInventoryId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_InventoryLedgers_DocumentId"" ON public.""InventoryLedgers"" (""DocumentId"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"InventoryLedgers\" CASCADE;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"DocumentDetails\" CASCADE;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"Documents\" CASCADE;");
        }
    }
}
