using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MenuGoBE.Migrations
{
    /// <inheritdoc />
    public partial class UpdateDocumentAndDocumentDetailFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"DocumentDetails\" DROP CONSTRAINT IF EXISTS \"FK_DocumentDetails_Recipes_RecipeId\";");
            migrationBuilder.Sql("ALTER TABLE \"Documents\" DROP CONSTRAINT IF EXISTS \"FK_Documents_Documents_FatherId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_DocumentDetails_RecipeId\";");
            migrationBuilder.Sql("ALTER TABLE \"DocumentDetails\" DROP COLUMN IF EXISTS \"RecipeId\";");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Documents' AND column_name='TotalPrice') THEN
        ALTER TABLE ""Documents"" RENAME COLUMN ""TotalPrice"" TO ""TotalAmount"";
    ELSIF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Documents' AND column_name='TotalAmount') THEN
        ALTER TABLE ""Documents"" ADD COLUMN ""TotalAmount"" numeric(30,12) NOT NULL DEFAULT 0;
    END IF;
END $$;");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Documents' AND column_name='FatherId') THEN
        ALTER TABLE ""Documents"" RENAME COLUMN ""FatherId"" TO ""ParentDocumentId"";
    ELSIF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Documents' AND column_name='ParentDocumentId') THEN
        ALTER TABLE ""Documents"" ADD COLUMN ""ParentDocumentId"" bigint NULL;
    END IF;
END $$;");

            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_Documents_FatherId\";");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_Documents_ParentDocumentId\" ON \"Documents\" (\"ParentDocumentId\");");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Documents' AND column_name='BusinessDate') THEN
        ALTER TABLE ""Documents"" ADD COLUMN ""BusinessDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
    END IF;
END $$;");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Documents' AND column_name='PostingSequence') THEN
        ALTER TABLE ""Documents"" ADD COLUMN ""PostingSequence"" bigint GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name='FK_Documents_Documents_ParentDocumentId') THEN
        ALTER TABLE ""Documents"" ADD CONSTRAINT ""FK_Documents_Documents_ParentDocumentId"" FOREIGN KEY (""ParentDocumentId"") REFERENCES ""Documents"" (""Id"") ON DELETE RESTRICT;
    END IF;
END $$;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Documents_Documents_ParentDocumentId",
                table: "Documents");

            migrationBuilder.DropColumn(
                name: "BusinessDate",
                table: "Documents");

            migrationBuilder.DropColumn(
                name: "PostingSequence",
                table: "Documents");

            migrationBuilder.RenameColumn(
                name: "TotalAmount",
                table: "Documents",
                newName: "TotalPrice");

            migrationBuilder.RenameColumn(
                name: "ParentDocumentId",
                table: "Documents",
                newName: "FatherId");

            migrationBuilder.RenameIndex(
                name: "IX_Documents_ParentDocumentId",
                table: "Documents",
                newName: "IX_Documents_FatherId");

            migrationBuilder.AddColumn<long>(
                name: "RecipeId",
                table: "DocumentDetails",
                type: "bigint",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_DocumentDetails_RecipeId",
                table: "DocumentDetails",
                column: "RecipeId");

            migrationBuilder.AddForeignKey(
                name: "FK_DocumentDetails_Recipes_RecipeId",
                table: "DocumentDetails",
                column: "RecipeId",
                principalTable: "Recipes",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Documents_Documents_FatherId",
                table: "Documents",
                column: "FatherId",
                principalTable: "Documents",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
