using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MenuGoBE.Migrations
{
    /// <inheritdoc />
    public partial class Recreate7CoreTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS ""CashFlowDetails"" CASCADE;
                DROP TABLE IF EXISTS ""CashFlows"" CASCADE;
                DROP TABLE IF EXISTS ""InventoryLedgers"" CASCADE;
                DROP TABLE IF EXISTS ""DocumentDetails"" CASCADE;
                DROP TABLE IF EXISTS ""DocumentPartners"" CASCADE;
                DROP TABLE IF EXISTS ""Documents"" CASCADE;
                DROP TABLE IF EXISTS ""BInventories"" CASCADE;
                
                CREATE TABLE ""BInventories"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""BranchId"" bigint NOT NULL,
    ""ProductId"" bigint NOT NULL,
    ""Type"" text NOT NULL,
    ""Avg"" numeric(30,12) NOT NULL,
    ""LeftOver"" numeric(30,12) NOT NULL,
    ""Quantity"" numeric(21,3) NOT NULL,
    ""ChainActive"" boolean NOT NULL,
    ""BranchActive"" boolean NOT NULL,
    ""IsManageQuantity"" boolean NOT NULL,
    ""MinStorage"" numeric(18,3) NOT NULL,
    ""MaxStorage"" numeric(18,3) NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_BInventories"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_BInventories_Branches_BranchId"" FOREIGN KEY (""BranchId"") REFERENCES ""Branches"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_BInventories_Products_ProductId"" FOREIGN KEY (""ProductId"") REFERENCES ""Products"" (""Id"") ON DELETE RESTRICT
);

CREATE TABLE ""Documents"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""BranchId"" bigint NOT NULL,
    ""ParentDocumentId"" bigint,
    ""PostingSequence"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""BusinessDate"" timestamp with time zone NOT NULL,
    ""Code"" character varying(100) NOT NULL,
    ""Type"" text NOT NULL,
    ""Status"" text NOT NULL,
    ""TransferStatus"" text NOT NULL,
    ""TotalAmount"" numeric(30,12) NOT NULL,
    ""CreatedBy"" bigint,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""IsDeleted"" boolean NOT NULL,
    ""DeletedBy"" bigint,
    ""DeletedAt"" timestamp with time zone,
    CONSTRAINT ""PK_Documents"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_Documents_Accounts_CreatedBy"" FOREIGN KEY (""CreatedBy"") REFERENCES ""Accounts"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_Documents_Accounts_DeletedBy"" FOREIGN KEY (""DeletedBy"") REFERENCES ""Accounts"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_Documents_Branches_BranchId"" FOREIGN KEY (""BranchId"") REFERENCES ""Branches"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_Documents_Documents_ParentDocumentId"" FOREIGN KEY (""ParentDocumentId"") REFERENCES ""Documents"" (""Id"") ON DELETE RESTRICT
);

CREATE TABLE ""DocumentDetails"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""DocumentId"" bigint NOT NULL,
    ""BInventoryId"" bigint NOT NULL,
    ""Quantity"" numeric(21,3) NOT NULL,
    ""SystemQuantity"" numeric(21,3),
    ""UnitPrice"" numeric(30,12) NOT NULL,
    ""Note"" text,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_DocumentDetails"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_DocumentDetails_BInventories_BInventoryId"" FOREIGN KEY (""BInventoryId"") REFERENCES ""BInventories"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_DocumentDetails_Documents_DocumentId"" FOREIGN KEY (""DocumentId"") REFERENCES ""Documents"" (""Id"") ON DELETE RESTRICT
);

CREATE TABLE ""DocumentPartners"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""DocumentId"" bigint NOT NULL,
    ""PartnerId"" bigint NOT NULL,
    ""Cost"" numeric(30,12) NOT NULL,
    ""Note"" text,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_DocumentPartners"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_DocumentPartners_Documents_DocumentId"" FOREIGN KEY (""DocumentId"") REFERENCES ""Documents"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_DocumentPartners_Partners_PartnerId"" FOREIGN KEY (""PartnerId"") REFERENCES ""Partners"" (""Id"") ON DELETE RESTRICT
);

CREATE TABLE ""CashFlows"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""BranchId"" bigint NOT NULL,
    ""PostingSequence"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""Code"" character varying(100) NOT NULL,
    ""BusinessDate"" timestamp with time zone NOT NULL,
    ""Direction"" text NOT NULL,
    ""Status"" text NOT NULL,
    ""TotalAmount"" numeric(30,12) NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""IsDeleted"" boolean NOT NULL,
    ""DeletedBy"" bigint,
    ""DeletedAt"" timestamp with time zone,
    CONSTRAINT ""PK_CashFlows"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_CashFlows_Accounts_DeletedBy"" FOREIGN KEY (""DeletedBy"") REFERENCES ""Accounts"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_CashFlows_Branches_BranchId"" FOREIGN KEY (""BranchId"") REFERENCES ""Branches"" (""Id"") ON DELETE RESTRICT
);

CREATE TABLE ""CashFlowDetails"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""CashFlowId"" bigint NOT NULL,
    ""DocumentPartnerId"" bigint,
    ""PartnerId"" bigint,
    ""Type"" text NOT NULL,
    ""PaymentMethod"" text NOT NULL,
    ""Amount"" numeric(30,12) NOT NULL,
    ""Note"" text,
    CONSTRAINT ""PK_CashFlowDetails"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_CashFlowDetails_CashFlows_CashFlowId"" FOREIGN KEY (""CashFlowId"") REFERENCES ""CashFlows"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_CashFlowDetails_DocumentPartners_DocumentPartnerId"" FOREIGN KEY (""DocumentPartnerId"") REFERENCES ""DocumentPartners"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_CashFlowDetails_Partners_PartnerId"" FOREIGN KEY (""PartnerId"") REFERENCES ""Partners"" (""Id"") ON DELETE RESTRICT
);

CREATE TABLE ""InventoryLedgers"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""BInventoryId"" bigint NOT NULL,
    ""DocumentId"" bigint,
    ""DocumentDetailId"" bigint,
    ""PostingSequence"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""BusinessDate"" timestamp with time zone NOT NULL,
    ""DocumentType"" text NOT NULL,
    ""QuantityDelta"" numeric(21,3) NOT NULL,
    ""InventoryValueDelta"" numeric(30,12) NOT NULL,
    ""RunningQuantity"" numeric(21,3) NOT NULL,
    ""RunningInventoryValue"" numeric(30,12) NOT NULL,
    ""RunningAverageCost"" numeric(30,12) NOT NULL,
    ""RunningLeftOver"" numeric(30,12) NOT NULL,
    ""ActualQuantity"" numeric(21,3),
    ""VarianceQuantity"" numeric(21,3),
    ""UnitCost"" numeric(30,12) NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""CreatedBy"" bigint,
    CONSTRAINT ""PK_InventoryLedgers"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_InventoryLedgers_Accounts_CreatedBy"" FOREIGN KEY (""CreatedBy"") REFERENCES ""Accounts"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_InventoryLedgers_BInventories_BInventoryId"" FOREIGN KEY (""BInventoryId"") REFERENCES ""BInventories"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_InventoryLedgers_DocumentDetails_DocumentDetailId"" FOREIGN KEY (""DocumentDetailId"") REFERENCES ""DocumentDetails"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_InventoryLedgers_Documents_DocumentId"" FOREIGN KEY (""DocumentId"") REFERENCES ""Documents"" (""Id"") ON DELETE RESTRICT
);

CREATE INDEX ""IX_BInventories_BranchId"" ON ""BInventories"" (""BranchId"");

CREATE INDEX ""IX_BInventories_ProductId"" ON ""BInventories"" (""ProductId"");

CREATE INDEX ""IX_Documents_BranchId"" ON ""Documents"" (""BranchId"");

CREATE UNIQUE INDEX ""IX_Documents_Code"" ON ""Documents"" (""Code"");

CREATE INDEX ""IX_Documents_CreatedBy"" ON ""Documents"" (""CreatedBy"");

CREATE INDEX ""IX_Documents_DeletedBy"" ON ""Documents"" (""DeletedBy"");

CREATE INDEX ""IX_Documents_ParentDocumentId"" ON ""Documents"" (""ParentDocumentId"");

CREATE INDEX ""IX_DocumentDetails_BInventoryId"" ON ""DocumentDetails"" (""BInventoryId"");

CREATE INDEX ""IX_DocumentDetails_DocumentId"" ON ""DocumentDetails"" (""DocumentId"");

CREATE INDEX ""IX_DocumentPartners_DocumentId"" ON ""DocumentPartners"" (""DocumentId"");

CREATE INDEX ""IX_DocumentPartners_PartnerId"" ON ""DocumentPartners"" (""PartnerId"");

CREATE INDEX ""IX_CashFlows_BranchId"" ON ""CashFlows"" (""BranchId"");

CREATE UNIQUE INDEX ""IX_CashFlows_Code"" ON ""CashFlows"" (""Code"");

CREATE INDEX ""IX_CashFlows_DeletedBy"" ON ""CashFlows"" (""DeletedBy"");

CREATE INDEX ""IX_CashFlowDetails_CashFlowId"" ON ""CashFlowDetails"" (""CashFlowId"");

CREATE INDEX ""IX_CashFlowDetails_DocumentPartnerId"" ON ""CashFlowDetails"" (""DocumentPartnerId"");

CREATE INDEX ""IX_CashFlowDetails_PartnerId"" ON ""CashFlowDetails"" (""PartnerId"");

CREATE INDEX ""IX_InventoryLedgers_BInventoryId"" ON ""InventoryLedgers"" (""BInventoryId"");

CREATE INDEX ""IX_InventoryLedgers_CreatedBy"" ON ""InventoryLedgers"" (""CreatedBy"");

CREATE INDEX ""IX_InventoryLedgers_DocumentDetailId"" ON ""InventoryLedgers"" (""DocumentDetailId"");

CREATE INDEX ""IX_InventoryLedgers_DocumentId"" ON ""InventoryLedgers"" (""DocumentId"");

");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}


